name = "w"
type = "javascript"
workers_dev = true

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
type = "Text"
globs = ["**/*.txt"]